In [1]:
import pandas as pd

In [2]:
p0 = pd.read_csv('./config/p0_reference.csv')
p0.head()

,rule_id,event_id,persona,event_name,role,age_min,age_max,sex,condition,horizon,...,source_denominator,conditioning_prevalence,calculation_method,lambda_annual,p0_value,scenario,evidence_status,use_status,source,scientific_note
0,R001,E01,P1,Asthme actuel au début,État initial,6,10.0,Tous,Aucune,Baseline,...,100,NaN,BASELINE_PREVALENCE,NaN,0.090000,CENTRAL,DIRECTE_AGE_GENERIQUE,UTILISABLE_AVEC_LIMITATION,Santé publique France / étude pédiatrique nati...,Valeur nationale pédiatrique; l'âge source n'e...
1,R002,E01,P5,Asthme préexistant,État imposé par le plan expérimental,25,49.0,Tous,Persona P5,Baseline,...,1,NaN,DESIGN_FIXED,NaN,1.000000,CENTRAL,DESIGN_DOCUMENTE,UTILISABLE,Définition de la persona validée,P5 est recrutée/simulée comme population asthm...
2,R003,E01,P5,Prévalence adulte de l'asthme — hommes,Cible externe de calibration,25,49.0,Homme,Population générale,Baseline,...,100,NaN,CALIBRATION_TARGET,NaN,0.051000,CALIBRATION,DIRECTE_NATIONALE,NE_PAS_TIRER_P5,"Cohorte CONSTANCES, France",Référence de population générale; P5 reste ast...
3,R004,E01,P5,Prévalence adulte de l'asthme — femmes,Cible externe de calibration,25,49.0,Femme,Population générale,Baseline,...,100,NaN,CALIBRATION_TARGET,NaN,0.064000,CALIBRATION,DIRECTE_NATIONALE,NE_PAS_TIRER_P5,"Cohorte CONSTANCES, France",Référence de population générale; P5 reste ast...
4,R005,E02,P1,Hospitalisation pour asthme,Événement récurrent,5,9.0,Homme,Asthme préexistant,Annuel,...,10000,0.09,ADAPTED_CONDITIONAL_RATE,0.027444,0.027071,CENTRAL,ADAPTATION_DOCUMENTEE,UTILISABLE_V1,"Santé publique France, PMSI + prévalence natio...",Adaptation: taux populationnel divisé par la p...

In [5]:
p0[['persona','event_name','role','age_min','age_max','sex','condition','source', 'source_denominator', 'source_measure','source_value']].head()

,persona,event_name,role,age_min,age_max,sex,condition,source,source_denominator,source_measure,source_value
0,P1,Asthme actuel au début,État initial,6,10.0,Tous,Aucune,Santé publique France / étude pédiatrique nati...,100,Prévalence,9.0
1,P5,Asthme préexistant,État imposé par le plan expérimental,25,49.0,Tous,Persona P5,Définition de la persona validée,1,Plan expérimental,1.0
2,P5,Prévalence adulte de l'asthme — hommes,Cible externe de calibration,25,49.0,Homme,Population générale,"Cohorte CONSTANCES, France",100,Prévalence,5.1
3,P5,Prévalence adulte de l'asthme — femmes,Cible externe de calibration,25,49.0,Femme,Population générale,"Cohorte CONSTANCES, France",100,Prévalence,6.4
4,P1,Hospitalisation pour asthme,Événement récurrent,5,9.0,Homme,Asthme préexistant,"Santé publique France, PMSI + prévalence natio...",10000,Taux populationnel de séjours,24.7